# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.CharField(max_length=100)),
                ('news_day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a news category (e.g. politics, sports etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the news', max_length=1000)),
                ('link', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">link number</a>', max_length=13, verbose_name='link')),
                ('category', models.ManyToManyField(help_text='Select a genre for this news', to='catalog.Genre')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.date')),
            ],
        ),
    ]
